//---------------------------------------------------------------------------

#ifndef PropertyH
#define PropertyH
//---------------------------------------------------------------------------
#include <string>
#include <memory>
#include <vector>
#include <map>
#include <variant>
#include <optional>
#include <functional>
#include <typeinfo>
#include <typeindex>
#include <chrono>

// Для совместимости с C++ Builder VCL
#ifdef __BORLANDC__
#include <System.Classes.hpp>
#include <System.SysUtils.hpp>
#include <Vcl.Graphics.hpp>
#endif

// Forward declarations

class MetaObject;

/**
 * @enum PropertyType
 * @brief Типы свойств метаданных
 */
enum class PropertyType {
	Unknown = 0,
	Requisite,           // Реквизит
	Column,              // Колонка/Графа
	Form,                // Форма
	Command,             // Команда
	Layout,              // Макет
	TablePart,           // Табличная часть
	Dimension,           // Измерение (для регистров)
	Resource,            // Ресурс (для регистров)
	Recalculation,       // Перерасчет (для регистров расчета)
	Custom               // Пользовательский тип свойства
};

/**
 * @enum DataType
 * @brief Типы данных для свойств
 */
enum class DataType {
    Unknown = 0,
    String,              // Строка
    Number,              // Число (целое или с плавающей точкой)
    Integer,             // Целое число
    Float,               // Число с плавающей точкой
    Boolean,             // Логический тип
	Date,                // Дата
    DateTime,            // Дата и время
    Time,                // Время
    Binary,              // Двоичные данные
    Reference,           // Ссылка на другой объект
    Table,               // Таблица значений
    ValueList,           // Список значений
    Enum,                // Перечисление
    UUID,                // Уникальный идентификатор
    XML,                 // XML данные
    JSON                 // JSON данные
};

/**
 * @enum PropertyFlags
 * @brief Флаги свойств (битовая маска)
 */
enum PropertyFlags : uint32_t {
    PF_None           = 0x0000,
	PF_Required       = 0x0001,  // Обязательное свойство
    PF_ReadOnly       = 0x0002,  // Только для чтения
    PF_Hidden         = 0x0004,  // Скрытое свойство
    PF_System         = 0x0008,  // Системное свойство
    PF_Calculated     = 0x0010,  // Вычисляемое свойство
    PF_Temporary      = 0x0020,  // Временное свойство
    PF_Indexed        = 0x0040,  // Индексируемое свойство
    PF_Unique         = 0x0080,  // Уникальное значение
    PF_Password       = 0x0100,  // Пароль (скрывать при вводе)
    PF_Multiline      = 0x0200,  // Многострочный текст
    PF_RichText       = 0x0400,  // Форматированный текст
    PF_History        = 0x0800,  // Ведется история изменений
    PF_FullTextSearch = 0x1000,  // Участвует в полнотекстовом поиске
    PF_AutoGenerated  = 0x2000,  // Автогенерируемое значение
    PF_Translatable   = 0x4000   // Переводимое свойство (синонимы)
};

/**
 * @struct ValidationRule
 * @brief Правило валидации значения свойства
 */
struct ValidationRule {
    std::string name;                    // Название правила
    std::string expression;              // Выражение для валидации
    std::string errorMessage;            // Сообщение об ошибке
    std::string description;             // Описание правила

    // Операторы сравнения
    bool operator==(const ValidationRule& other) const {
        return name == other.name &&
               expression == other.expression &&
               errorMessage == other.errorMessage &&
               description == other.description;
    }

    bool operator!=(const ValidationRule& other) const {
        return !(*this == other);
    }
};

/**
 * @class Property
 * @brief Базовый абстрактный класс для всех свойств метаданных
 *
 * Реализует общий интерфейс и функциональность для всех типов свойств:
 * - Реквизиты
 * - Колонки
 * - Формы
 * - Команды
 * - Макеты
 * - Табличные части
 */
class Property : public std::enable_shared_from_this<Property> {
public:
    // ========== Конструкторы и деструктор ==========

    /**
	 * @brief Конструктор по умолчанию
     */
    Property();

    /**
     * @brief Конструктор с параметрами
     * @param name Имя свойства
     * @param type Тип свойства
     * @param description Описание
     */
    Property(const std::string& name,
             PropertyType type = PropertyType::Unknown,
             const std::string& description = "");

    /**
     * @brief Виртуальный деструктор
     */
    virtual ~Property();

	// Запрещаем копирование, разрешаем перемещение
    Property(const Property&) = delete;
    Property& operator=(const Property&) = delete;
    Property(Property&&) noexcept;
    Property& operator=(Property&&) noexcept;

    // ========== Идентификация и информация о типе ==========

    /**
     * @brief Получить тип свойства
     * @return Тип свойства
     */
    virtual PropertyType getPropertyType() const = 0;

    /**
     * @brief Получить имя типа свойства
     * @return Строковое представление типа
     */
    virtual std::string getPropertyTypeName() const = 0;

    /**
     * @brief Получить уникальный идентификатор свойства
     * @return UUID свойства
     */
    std::string getUUID() const;

    /**
     * @brief Сравнить типы свойств
     * @param other Другое свойство
     * @return true, если свойства одного типа
     */
    virtual bool isSameType(const Property& other) const;

    /**
     * @brief Проверить, является ли свойство указанного типа
     * @tparam T Тип для проверки
     * @return true, если свойство является экземпляром T или его потомком
     */
	template<typename T>
    bool isInstanceOf() const;

    /**
     * @brief Привести свойство к указанному типу
     * @tparam T Целевой тип
     * @return Указатель на свойство типа T или nullptr
     */
    template<typename T>
    T* as();

    template<typename T>
    const T* as() const;

    // ========== Основные свойства ==========

    /**
     * @brief Установить имя свойства
     * @param name Новое имя
	 */
    void setName(const std::string& name);

    /**
     * @brief Получить имя свойства
     * @return Имя свойства
     */
    std::string getName() const;

    /**
     * @brief Установить синоним
     * @param synonym Новый синоним
     */
    void setSynonym(const std::string& synonym);

    /**
     * @brief Получить синоним
     * @return Синоним свойства
     */
	std::string getSynonym() const;

    /**
     * @brief Установить описание
     * @param description Новое описание
     */
    void setDescription(const std::string& description);

    /**
     * @brief Получить описание
     * @return Описание свойства
	 */
    std::string getDescription() const;

    /**
     * @brief Установить тип данных
     * @param dataType Тип данных
     */
	void setDataType(DataType dataType);

    /**
     * @brief Получить тип данных
     * @return Тип данных свойства
     */
    DataType getDataType() const;

    /**
     * @brief Получить имя типа данных
     * @return Строковое представление типа данных
     */
    std::string getDataTypeName() const;

    /**
     * @brief Установить флаги свойства
     * @param flags Новые флаги
     */
    void setFlags(uint32_t flags);

	/**
     * @brief Получить флаги свойства
     * @return Флаги свойства
     */
    uint32_t getFlags() const;

    /**
     * @brief Добавить флаг
     * @param flag Флаг для добавления
     */
    void addFlag(PropertyFlags flag);

    /**
     * @brief Удалить флаг
     * @param flag Флаг для удаления
     */
    void removeFlag(PropertyFlags flag);

    /**
	 * @brief Проверить наличие флага
     * @param flag Флаг для проверки
     * @return true, если флаг установлен
     */
    bool hasFlag(PropertyFlags flag) const;

    /**
     * @brief Проверить, является ли свойство обязательным
     * @return true, если свойство обязательное
     */
    bool isRequired() const;

    /**
     * @brief Проверить, является ли свойство только для чтения
     * @return true, если свойство только для чтения
     */
    bool isReadOnly() const;

    /**
	 * @brief Проверить, является ли свойство скрытым
     * @return true, если свойство скрытое
     */
    bool isHidden() const;

    /**
     * @brief Проверить, является ли свойство системным
     * @return true, если свойство системное
     */
    bool isSystem() const;

    /**
     * @brief Установить значение по умолчанию
     * @param value Значение по умолчанию
     */
    void setDefaultValue(const std::string& value);

    /**
     * @brief Получить значение по умолчанию
	 * @return Значение по умолчанию
     */
    std::string getDefaultValue() const;

    /**
     * @brief Установить сортировку
     * @param sortOrder Порядок сортировки (0 - не сортируется, >0 - порядок)
     */
    void setSortOrder(int sortOrder);

    /**
     * @brief Получить сортировку
     * @return Порядок сортировки
     */
    int getSortOrder() const;

    /**
     * @brief Установить группу свойств
     * @param group Группа
	 */
    void setGroup(const std::string& group);

    /**
     * @brief Получить группу свойств
     * @return Группа
     */
    std::string getGroup() const;

    /**
     * @brief Установить категорию
     * @param category Категория
     */
    void setCategory(const std::string& category);

    /**
     * @brief Получить категорию
     * @return Категория
     */
	std::string getCategory() const;

    /**
     * @brief Установить дату создания
     * @param created Дата создания
     */
    void setCreated(const std::chrono::system_clock::time_point& created);

    /**
     * @brief Получить дату создания
     * @return Дата создания
     */
    std::chrono::system_clock::time_point getCreated() const;

    /**
     * @brief Установить дату последнего изменения
     * @param modified Дата изменения
     */
    void setModified(const std::chrono::system_clock::time_point& modified);

    /**
     * @brief Получить дату последнего изменения
     * @return Дата изменения
     */
    std::chrono::system_clock::time_point getModified() const;

    /**
     * @brief Обновить дату изменения на текущее время
     */
    void updateModified();

    /**
     * @brief Получить строковое представление даты создания
     * @param format Формат даты (по умолчанию: "%Y-%m-%d %H:%M:%S")
     * @return Строка с датой
     */
    std::string getCreatedString(const std::string& format = "%Y-%m-%d %H:%M:%S") const;

	/**
     * @brief Получить строковое представление даты изменения
     * @param format Формат даты
     * @return Строка с датой
     */
    std::string getModifiedString(const std::string& format = "%Y-%m-%d %H:%M:%S") const;

    // ========== Значения и валидация ==========

    /**
     * @brief Установить текущее значение
     * @param value Новое значение
     * @return true, если значение установлено успешно
     */
    virtual bool setValue(const std::string& value);

    /**
     * @brief Получить текущее значение
     * @return Текущее значение
	 */
    virtual std::string getValue() const;

    /**
     * @brief Очистить значение (установить в значение по умолчанию или пустое)
     */
    virtual void clearValue();

    /**
     * @brief Проверить, установлено ли значение
     * @return true, если значение установлено
     */
    virtual bool hasValue() const;

    /**
     * @brief Добавить правило валидации
     * @param rule Правило валидации
     */
    void addValidationRule(const ValidationRule& rule);

    /**
     * @brief Удалить правило валидации по имени
     * @param ruleName Имя правила
     * @return true, если правило было удалено
     */
    bool removeValidationRule(const std::string& ruleName);

    /**
     * @brief Получить все правила валидации
     * @return Вектор правил валидации
     */
    std::vector<ValidationRule> getValidationRules() const;

    /**
     * @brief Проверить валидность текущего значения
     * @param errors Вектор для записи ошибок
     * @return true, если значение валидно
     */
	virtual bool validate(std::vector<std::string>& errors) const;

    /**
     * @brief Проверить валидность конкретного значения
     * @param value Значение для проверки
     * @param errors Вектор для записи ошибок
     * @return true, если значение валидно
     */
    virtual bool validateValue(const std::string& value, std::vector<std::string>& errors) const;

    /**
     * @brief Получить минимальное допустимое значение (для числовых типов)
     * @return Минимальное значение
     */
    std::optional<double> getMinValue() const;

    /**
     * @brief Установить минимальное допустимое значение
     * @param minValue Минимальное значение
	 */
    void setMinValue(double minValue);

    /**
     * @brief Получить максимальное допустимое значение (для числовых типов)
     * @return Максимальное значение
     */
    std::optional<double> getMaxValue() const;

    /**
     * @brief Установить максимальное допустимое значение
     * @param maxValue Максимальное значение
     */
    void setMaxValue(double maxValue);

    /**
     * @brief Получить минимальную длину (для строковых типов)
     * @return Минимальная длина
     */
	std::optional<size_t> getMinLength() const;

    /**
     * @brief Установить минимальную длину
     * @param minLength Минимальная длина
     */
    void setMinLength(size_t minLength);

    /**
     * @brief Получить максимальную длину (для строковых типов)
     * @return Максимальная длина
     */
    std::optional<size_t> getMaxLength() const;

    /**
     * @brief Установить максимальную длину
     * @param maxLength Максимальная длина
     */
    void setMaxLength(size_t maxLength);

    /**
     * @brief Получить регулярное выражение для валидации (для строковых типов)
     * @return Регулярное выражение
     */
    std::optional<std::string> getRegExp() const;

    /**
     * @brief Установить регулярное выражение для валидации
     * @param regExp Регулярное выражение
     */
    void setRegExp(const std::string& regExp);

    // ========== Паттерн Visitor ==========

    /**
     * @brief Принять посетителя
     * @param visitor Указатель на посетителя
     */
	//virtual void accept(PropertyVisitor* visitor) = 0;

    // ========== Паттерн Prototype ==========

    /**
     * @brief Создать глубокую копию свойства
     * @return Уникальный указатель на копию
     */
    virtual std::unique_ptr<Property> clone() const = 0;

    /**
     * @brief Создать глубокую копию с новым именем
     * @param newName Новое имя для копии
     * @return Уникальный указатель на копию
     */
    virtual std::unique_ptr<Property> cloneWithName(const std::string& newName) const;

    // ========== Сериализация ==========

    /**
     * @brief Сериализовать свойство в XML
     * @param parent Родительский XML элемент
     */
    virtual void toXML(void* parent) const;

    /**
     * @brief Десериализовать свойство из XML
     * @param element XML элемент
     * @return true, если десериализация успешна
     */
    virtual bool fromXML(const void* element);

    /**
     * @brief Сериализовать свойство в JSON
     * @return JSON представление свойства
     */
    virtual std::string toJSON() const;

    /**
     * @brief Десериализовать свойство из JSON
     * @param json JSON строка
     * @return true, если десериализация успешна
     */
    virtual bool fromJSON(const std::string& json);

    // ========== Работа с UI (C++ Builder VCL) ==========

#ifdef __BORLANDC__
    /**
     * @brief Заполнить TreeView узлами свойства
     * @param parent Родительский узел TreeView
     * @param treeView Указатель на TreeView
     */
    virtual void populateTreeView(TTreeNode* parent, TTreeView* treeView) const;

    /**
     * @brief Получить свойства для отображения в PropertyGrid
     * @return StringList с парами "ключ-значение"
     */
    virtual TStringList* getDisplayProperties() const;

    /**
     * @brief Получить иконку для TreeView
     * @return Индекс иконки в ImageList
     */
    virtual int getTreeViewIconIndex() const;

    /**
     * @brief Получить цвет текста для TreeView
     * @return Цвет текста
     */
    virtual TColor getTreeViewTextColor() const;

    /**
     * @brief Создать компонент для редактирования свойства
     * @param parent Родительский компонент
     * @return Указатель на созданный компонент
     */
	virtual TWinControl* createEditor(TWinControl* parent) const;

    /**
     * @brief Загрузить значение из компонента редактора
     * @param editor Компонент редактора
     * @return true, если значение успешно загружено
     */
    virtual bool loadFromEditor(TWinControl* editor);

    /**
     * @brief Сохранить значение в компонент редактора
     * @param editor Компонент редактора
     */
    virtual void saveToEditor(TWinControl* editor) const;
#endif

    // ========== Сравнение свойств ==========

    /**
     * @brief Сравнить свойства по содержимому
     * @param other Другое свойство
     * @param differences Вектор для записи различий
     * @return true, если свойства идентичны
     */
    virtual bool compare(const Property& other,
                        std::vector<std::string>& differences) const;

    /**
     * @brief Сравнить имена свойств
     * @param other Другое свойство
     * @return true, если имена совпадают
     */
    bool compareByName(const Property& other) const;

    /**
     * @brief Оператор сравнения (по имени)
     * @param other Другое свойство
     * @return true, если имена совпадают
     */
    bool operator==(const Property& other) const;

    bool operator!=(const Property& other) const;

    /**
     * @brief Оператор сравнения для сортировки (по имени)
     * @param other Другое свойство
     * @return true, если текущее свойство меньше другого
     */
    bool operator<(const Property& other) const;

    // ========== Зависимости и связи ==========

    /**
     * @brief Установить владельца свойства
	 * @param owner Слабая ссылка на владельца (MetaObject)
     */
    void setOwner(const std::weak_ptr<MetaObject>& owner);

    /**
     * @brief Получить владельца свойства
     * @return Указатель на владельца или nullptr
     */
    std::shared_ptr<MetaObject> getOwner() const;

    /**
     * @brief Установить связанное свойство (например, для ссылочных типов)
     * @param property Связанное свойство
     */
    void setLinkedProperty(const std::weak_ptr<Property>& property);

    /**
     * @brief Получить связанное свойство
     * @return Указатель на связанное свойство или nullptr
     */
    std::shared_ptr<Property> getLinkedProperty() const;

    /**
     * @brief Добавить зависимое свойство
     * @param property Зависимое свойство
     */
    void addDependentProperty(const std::weak_ptr<Property>& property);

    /**
     * @brief Получить список зависимых свойств
     * @return Вектор слабых указателей на зависимые свойства
     */
    std::vector<std::weak_ptr<Property>> getDependentProperties() const;

    /**
     * @brief Проверить, зависит ли свойство от другого
     * @param property Свойство для проверки
     * @return true, если текущее свойство зависит от проверяемого
     */
    bool dependsOn(const std::shared_ptr<Property>& property) const;

    // ========== Расширяемые атрибуты ==========

    /**
     * @brief Установить расширенный атрибут
     * @param key Ключ атрибута
     * @param value Значение (строка, число, bool)
     */
    void setAttribute(const std::string& key,
                     const std::variant<std::string, int, double, bool>& value);

    /**
     * @brief Получить расширенный атрибут
     * @param key Ключ атрибута
     * @return optional с значением атрибута
     */
    std::optional<std::variant<std::string, int, double, bool>>
    getAttribute(const std::string& key) const;

    /**
     * @brief Удалить расширенный атрибут
     * @param key Ключ атрибута
     * @return true, если атрибут был удален
     */
    bool removeAttribute(const std::string& key);

    /**
     * @brief Получить все расширенные атрибуты
     * @return Словарь расширенных атрибутов
     */
    std::map<std::string, std::variant<std::string, int, double, bool>>
    getAllAttributes() const;

    // ========== Сигналы и события ==========

    using ValueChangedSignal = std::function<void(const std::string& oldValue,
                                                  const std::string& newValue)>;
    using PropertyModifiedSignal = std::function<void()>;

    /**
     * @brief Подписаться на изменение значения
     * @param callback Функция обратного вызова
     * @return Идентификатор подписки
     */
    size_t subscribeToValueChanged(ValueChangedSignal callback);

    /**
     * @brief Подписаться на изменение свойства
     * @param callback Функция обратного вызова
     * @return Идентификатор подписки
     */
    size_t subscribeToPropertyModified(PropertyModifiedSignal callback);

    /**
     * @brief Отписаться от события
     * @param subscriptionId Идентификатор подписки
     */
    void unsubscribe(size_t subscriptionId);

    // ========== Статические методы ==========

    /**
     * @brief Преобразовать тип свойства в строку
     * @param type Тип свойства
     * @return Строковое представление
     */
    static std::string propertyTypeToString(PropertyType type);

    /**
     * @brief Преобразовать строку в тип свойства
     * @param typeName Имя типа
     * @return Тип свойства
     */
    static PropertyType stringToPropertyType(const std::string& typeName);

    /**
     * @brief Преобразовать тип данных в строку
     * @param dataType Тип данных
     * @return Строковое представление
     */
    static std::string dataTypeToString(DataType dataType);

    /**
     * @brief Преобразовать строку в тип данных
     * @param typeName Имя типа данных
     * @return Тип данных
     */
    static DataType stringToDataType(const std::string& typeName);

    /**
     * @brief Проверить, является ли имя свойства валидным
     * @param name Имя для проверки
     * @param error Сообщение об ошибке (если есть)
     * @return true, если имя валидно
     */
    static bool isValidName(const std::string& name, std::string& error);

protected:
    // Основные свойства
    std::string name;
    std::string synonym;
    std::string description;
    PropertyType propertyType;
    DataType dataType;
    uint32_t flags;
    std::string defaultValue;
    std::string currentValue;
    int sortOrder;
    std::string group;
    std::string category;

    // Временные метки
    std::chrono::system_clock::time_point created;
    std::chrono::system_clock::time_point modified;

    // Идентификатор
    std::string uuid;

    // Владелец и связи
    std::weak_ptr<MetaObject> owner;
    std::weak_ptr<Property> linkedProperty;
    std::vector<std::weak_ptr<Property>> dependentProperties;

    // Валидация
    std::vector<ValidationRule> validationRules;
    std::optional<double> minValue;
    std::optional<double> maxValue;
    std::optional<size_t> minLength;
    std::optional<size_t> maxLength;
    std::optional<std::string> regExp;

    // Расширенные атрибуты
    std::map<std::string, std::variant<std::string, int, double, bool>> attributes;

    // Сигналы
	struct SignalData {
        size_t nextId = 1;
        std::map<size_t, ValueChangedSignal> valueChangedCallbacks;
        std::map<size_t, PropertyModifiedSignal> propertyModifiedCallbacks;
    };
    std::shared_ptr<SignalData> signalData;

    // Вспомогательные методы
    void notifyValueChanged(const std::string& oldValue, const std::string& newValue);
    void notifyPropertyModified();

    // Генерация UUID
    static std::string generateUUID();

    // Проверка и нормализация имени
    static std::string normalizeName(const std::string& name);

    // Валидация значения в зависимости от типа данных
    bool validateDataType(const std::string& value, std::vector<std::string>& errors) const;
    bool validateString(const std::string& value, std::vector<std::string>& errors) const;
    bool validateNumber(const std::string& value, std::vector<std::string>& errors) const;
    bool validateInteger(const std::string& value, std::vector<std::string>& errors) const;
    bool validateFloat(const std::string& value, std::vector<std::string>& errors) const;
    bool validateBoolean(const std::string& value, std::vector<std::string>& errors) const;
    bool validateDate(const std::string& value, std::vector<std::string>& errors) const;
    bool validateDateTime(const std::string& value, std::vector<std::string>& errors) const;
    bool validateTime(const std::string& value, std::vector<std::string>& errors) const;

private:
    // Инициализация объекта
    void initialize();
};

// ========== Вспомогательные шаблоны ==========

/**
 * @brief Вспомогательный класс для безопасного приведения типов свойств
 */
template<typename T>
class PropertyCast {
public:
    static T* cast(Property* prop) {
        return dynamic_cast<T*>(prop);
    }

	static const T* cast(const Property* prop) {
		return dynamic_cast<const T*>(prop);
	}

	static std::shared_ptr<T> cast(const std::shared_ptr<Property>& prop) {
		return std::dynamic_pointer_cast<T>(prop);
	}
};

// Макрос для удобного приведения типов
#define PROPERTY_CAST(Type, prop) PropertyCast<Type>::cast(prop)

#endif // PROPERTY_H







